port: ":8000"
"KEY_FOR_SIGNATURE_JWT": "jwt_key"

db:
  pos: "postgres"
  username: "postgres"
  host: "localhost" #localhost/postgres
  port: "5432"
  dbase: "postgres"


mongodb:
  username: "root"
  port: "27017"
  dbase: "mongodb"
  collection: "mongocl"

